name: Test Version Command

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ master ]

jobs:
  test-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Run Docker version test
        run: |
          make docker-test-version
